# Generated by Django 4.2.2 on 2023-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=264)),
                ('answer', models.CharField(max_length=264)),
                ('createDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=264)),
                ('createDate', models.DateField()),
            ],
        ),
    ]
