# Generated by Django 4.2.2 on 2023-06-07 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=5000),
        ),
    ]
